apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndpt-vue
  labels:
    app: ndpt-vue    
spec:
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 0 
      maxSurge: 2
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: ndpt-vue
  template:
    metadata:
      labels:
        app: ndpt-vue
    spec:
      containers:
      - name: ndpt-vue
        image: dev-nexus-docker.scrapmaster.co.kr/${TAG_ARTIFACTID}:${TAG_NAME}
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DEPLOY_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: APPLY_TIMESTAMP
            value: "${APPLY_TIMESTAMP}"
        ports:
           - containerPort: 80
        volumeMounts:
          - name: timezone-config
            mountPath: /etc/localtime
      volumes:
        - name: timezone-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
---
apiVersion: v1
kind: Service
metadata:
  name: ndpt-vue
spec:
  type: ClusterIP
  selector:
    app: ndpt-vue
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443

# 아래 URL로 연결한다
# ndpt.dahami.com
# ndpt.dahami.co.kr
# contextName : /