FROM nginx:latest

RUN sed -i '1idaemon off;' /etc/nginx/nginx.conf

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./dist/. /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html

EXPOSE 80

STOPSIGNAL SIGQUIT

CMD ["nginx"]
